BNo_Face/Controllers/BillController.cs
using BNo_Face.DataAccess.Data;
using BNo_Face.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BNo_Face.Controllers
{
	public class BillController : Controller
	{
		private readonly ApplicationDbContext _db;
		public BillController(ApplicationDbContext db)
		{
			_db = db;
		}

		public void LoadProduct()
		{
			IEnumerable<SelectListItem> productList = _db.Products.Select(
				u => new SelectListItem()
				{
					Text = u.ProductName,
					Value = u.ProductID.ToString()
				}
				).ToList();
			ViewBag.ProductList = productList;
		
		}

		public IActionResult Index()
		{
            LoadProduct();
            return View();
		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(string searchString)
		{
            //LoadProduct();
            // get cookies
            var cookie = Request.Cookies["userID"];
			// check cookie
			if (cookie == null)
			{
				return RedirectToAction("Index", "Home");
			}
			var bills = from u in _db.Bills 
							select u;
			
			if (!String.IsNullOrEmpty(searchString)) 
			{
				bills = bills.Where(c => c.BillID.ToString().Contains(searchString)); 
			}
			return View(bills);
		}
		public IActionResult Create()
		{
			LoadProduct();
			return View();

		}

		

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Bill bill)
		{
			LoadProduct();
			if (ModelState.IsValid)
			{

				_db.Bills.Add(bill);
				_db.SaveChanges();
				return RedirectToAction("Index");

			}
			return View(bill);
		}
		public IActionResult Edit(int? ID)
		{
			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			var s = _db.Bills.FirstOrDefault(u => u.BillID == ID);
			if (s == null)
			{
				return NotFound();
			}
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Bill bill)
		{
			if (ModelState.IsValid)
			{
				_db.Bills.Update(bill);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(bill);


		}
		public IActionResult Delete(int? ID)
		{

			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			var s = _db.Bills.FirstOrDefault(u => u.BillID == ID);
			if (s == null)
			{
				return NotFound();
			}
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(Bill bill)
		{
			
			if (ModelState.IsValid)
			{
				_db.Bills.Remove(bill);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(bill);


		}
		
	}
}

BNo_Face/Controllers/CategoryController.cs
using BNo_Face.DataAccess.Data;
using BNo_Face.Model;
using Microsoft.AspNetCore.Mvc;
using BNo_Face.DataAccess;

namespace BNo_Face.Controllers
{
	public class CategoryController : Controller
	{
		private readonly ApplicationDbContext _db;
		public CategoryController(ApplicationDbContext db)
		{
			_db = db;
		}
		public IActionResult Index(string searchString)

		{
			// get cookies
			var cookie = Request.Cookies["userID"];
            Console.WriteLine(cookie);
           
            
            // check cookie
            if (cookie == null)
			{
				return RedirectToAction("Index", "Home");
			}
			var categorys = from u in _db.Categories // lấy toàn bộ liên kết
						select u;

			if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
			{
				categorys = categorys.Where(c=> c.CategoryName.Contains(searchString) ); //lọc theo chuỗi tìm kiếm
			}
			return View(categorys);
		}
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Category category)
		{
		
			if (ModelState.IsValid)
			{
				
				_db.Categories.Add(category);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(category);
		}
		public IActionResult Edit(int? ID)
		{
			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			var s = _db.Categories.FirstOrDefault(u => u.CategoryID == ID);
			if (s == null)
			{
				return NotFound();
			}
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Category category)
		{

			if (ModelState.IsValid)
			{
				_db.Categories.Update(category);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(category);

			
		}
		public IActionResult Delete(int? ID)
		{

			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			var s = _db.Categories.FirstOrDefault(u => u.CategoryID == ID);
			if (s == null)
			{
				return NotFound();
			}
			Console.WriteLine(s.CategoryName.ToString()+ "" + s.CategoryID);
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(Category category)
		{
			Console.WriteLine(category.CategoryName.ToString() + "" + category.CategoryID);
			if (ModelState.IsValid)
			{
				_db.Categories.Remove(category);
				_db.SaveChanges();
				var s = _db.Categories.FirstOrDefault(u => u.CategoryID == category.CategoryID);
				if (s == null)
				{
					Console.WriteLine("Nah it's null");
				}
				return RedirectToAction("Index");
			}
			Console.WriteLine(category.CategoryName.ToString() + "" + category.CategoryID + "What?? ");
			return View(category);

			
		}

	}
}

BNo_Face/Controllers/ProductController.cs
using BNo_Face.DataAccess.Data;
using BNo_Face.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BNo_Face.Controllers
{
	public class ProductController : Controller
	{
		private readonly ApplicationDbContext _db;
		public ProductController(ApplicationDbContext db)
		{
			_db = db;
			_db.Products.Include(u => u.Category);
		}
		public void LoadCategory()
		{
			//ViewBag.CategoryID = new SelectList(_db.Categories, "CategoryID", "CategoryName");
			IEnumerable<SelectListItem> categoryList = _db.Categories.Select(
				u => new SelectListItem()
				{
					Text = u.CategoryName,
					Value = u.CategoryID.ToString()
				}
				).ToList();
			ViewBag.CategoryList = categoryList;
		}
		public IActionResult Index(string searchString)
		{
			
			// get cookies
			var cookie = Request.Cookies["userID"];
			
			// check cookie
			if (cookie == null)
			{
				return RedirectToAction("Index", "Home");
			}
			
			
			//show the list of products with Name of category

			var products = _db.Products.Include(u => u.Category).ToList();
			//searching
			if (!string.IsNullOrEmpty(searchString))
			{
				products = products.Where(u => u.ProductName.ToLower().Contains(searchString.ToLower())).ToList();
			}
			
			return View(products);
		}
		
		public IActionResult Create()
		{
			
			LoadCategory();
			return View();
		}
			
		
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Product product)
		{
			

			if (ModelState.IsValid)
			{
				Console.WriteLine(product.CategoryID);
				_db.Products.Add(product);
				_db.SaveChanges();
				return RedirectToAction("Index");
				
			}
			else
			{
				LoadCategory();
				return View(product);
			}
		}

		public IActionResult Edit(int? ID)
		{
			LoadCategory();
			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			var s = _db.Products.FirstOrDefault(u => u.ProductID == ID);
			if (s == null)
			{
				return NotFound();
			}
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Product product)
		{
			LoadCategory();
			if (ModelState.IsValid)
			{
				_db.Products.Update(product);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(product);


		}
		public IActionResult Delete(int? ID)
		{

			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			//var s = _db.Products.FirstOrDefault(u => u.ProductID == ID);
			var s = _db.Products.Include(p => p.Category).FirstOrDefault(u => u.ProductID == ID);
			if (s == null)
			{
				return NotFound();
			}
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(Product product)
		{

			if (ModelState.IsValid)
			{
				_db.Products.Remove(product);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(product);


		}
	}
}

BNo_Face/Controllers/UserController.cs
using BNo_Face.DataAccess.Data;
using BNo_Face.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace BNo_Face.Controllers
{
	
	public class UserController : Controller
	{
		private readonly ApplicationDbContext _db;
		public UserController(ApplicationDbContext db)
		{
			_db = db;
		}
		//tìm kiếm
		public IActionResult Index(string searchString)
		{
			// get cookies
			var cookie = Request.Cookies["userID"];
			// check cookie
			if (cookie == null)
			{
				return RedirectToAction("Index", "Home");
			}
			/*IEnumerable<User> userlist = _db.Users.ToList();
			return View(userlist);*/
			var users = from u in _db.Users // lấy toàn bộ liên kết
						select u;

			if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
			{
				users = users.Where(s => s.UserName.Contains(searchString) || s.NumberPhone.Contains(searchString)); //lọc theo chuỗi tìm kiếm
			}
			return View(users);
		}
		//tạo
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(User user)
		{
			if (user.UserName == user.Password)
			{
				ModelState.AddModelError("UserName", "Tên và mật khẩu không được trùng");
			}
			if(user.Birthday.Date > DateTime.Now)
			{
				ModelState.AddModelError("Birthday", "Ngày sinh phải nhỏ hơn ngày hiện tại");
			}


			if (ModelState.IsValid)
			{
				Console.WriteLine("Create user");
				_db.Users.Add(user);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			
			return View(user);
		}
		//sửa
		public IActionResult Edit(int? ID)
		{

			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			var s = _db.Users.FirstOrDefault(u => u.UserID == ID);
			if (s == null)
			{
				return NotFound();
			}
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(User user)
		{
			if (user.UserName == user.Password)
			{
				ModelState.AddModelError("UserName", "Tên và mật khẩu không được trùng");
			}
			if (user.Birthday.Date > DateTime.Now)
			{
				ModelState.AddModelError("Birthday", "Ngày sinh phải nhỏ hơn ngày hiện tại");
			}
			if (ModelState.IsValid)
			{
				Console.WriteLine("Edit user");
				_db.Users.Update(user);
				_db.SaveChanges();
				return RedirectToAction("Index");

			}
			return View(user);
			
		}
		//xóa
		public IActionResult Delete(int? ID)
		{

			if (ID == null || ID == 0)
			{
				return NotFound();
			}
			var s = _db.Users.FirstOrDefault(u => u.UserID == ID);
			if (s == null)
			{
				return NotFound();
			}
			return View(s);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(User user)
		{
			if (ModelState.IsValid)
			{
				Console.WriteLine("Delete user");
				_db.Users.Remove(user);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(user);
		
		}
		

	}
}

BNo_Face/Views/Category/Create.cshtml
@model Category
<body>

	<div class="container" >
		<form method="post" asp-action="Create" class="SignIn">
			<div class="border p-3 Backgroud_US">
				<div class="row pb-2">
					<h2>Danh Mục</h2>
				</div>
				<!--<div asp-validation-summary="All" class="text-danger"></div>-->
				<div class="mb-3">
					<label asp-for="CategoryName" class="title_block"></label>
					<input asp-for="CategoryName" class="textbox" /> <br />
					<span asp-validation-for="CategoryName" class="text-danger"></span>
				</div>

				<div class="bgr-bt">
					<button type="submit" class="btn btn-primary">Tạo Danh Mục</button>
					<button class="btn btn-primary" asp-controller="Category" asp-action="Index">Trở về</button>
				</div>
			</div>
		</form>
	</div>
</body>

BNo_Face/Views/Category/Delete.cshtml
@model Category

<form method="post" class="SignIn" asp-action="Delete">
	<div class="border p-3 Backgroud_US">
		<div class="row pb-2">
			<h2>Danh Mục</h2>
		</div>
		<!--<div asp-validation-summary="All" class="text-danger"></div>-->
		<input type="hidden" asp-for="CategoryID" />
		<div class="mb-3">
			<label asp-for="CategoryName" class="title_block"></label>
			<input asp-for="CategoryName" type="hidden" />
			<span class="textbox BorderShow">@Model.CategoryName</span>
			<span asp-validation-for="CategoryName" class="text-danger"></span>
		</div>
		<div class="Chia">
			<div class="Sbetween">
				<div class="bgr-xbt">
					<button type="submit" class="btn btn-primary" onclick="Send()">Xóa</button>
				</div>
				<div class="bgr-bt">
					<button class="btn btn-primary" asp-controller="Category" asp-action="Index">Trở về</button>
				</div>
			</div>
		</div>
	</div>
</form>

BNo_Face/Views/Category/Edit.cshtml
@model Category


@*<form method="post" asp-action="Edit"  class="SignIn">
	<div class="border p-3">
		<div class="row pb-2">
			<h2>Danh Mục</h2>
		</div>
		<!--<div asp-validation-summary="All" class="text-danger"></div>-->
		<div class="mb-3">
			<input type="hidden" asp-for="CategoryID" />
		</div>
		<div class="mb-3">
			<label asp-for="CategoryName" class="title_block"></label>
			<input asp-for="CategoryName" class="textbox" /> <br />
			<span asp-validation-for="CategoryName" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary">Sửa</button>
		<a asp-controller="Category" asp-action="Index">Trở về </a>
	</div>
</form>*@

<form method="post" asp-action="Edit" class="SignIn">
    <div class="border p-3 Backgroud_US">
        <div class="row pb-2">
            <h2>Danh Mục</h2>
        </div>
        <div class="mb-3">
            <input type="hidden" asp-for="CategoryID" /> <!-- Thêm trường ẩn để truyền CategoryID -->
            <label asp-for="CategoryName" class="title_block"></label>
            <input asp-for="CategoryName" class="textbox" /> <br />
            <span asp-validation-for="CategoryName" class="text-danger"></span>
        </div>
        <div class="bgr-bt">
            <button type="submit" class="btn btn-primary" onclick="confirmEdit()">Sửa</button>
            <button class="btn btn-primary" asp-controller="Category" asp-action="Index">Trở về</button>
        </div>
     </div>
</form>

BNo_Face/Views/Category/Index.cshtml
@model IEnumerable<Category>
<!--<header>
	<a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Index">BNo_Face</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
			aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<nav>

		<ul>
			<li><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Nhân Viên</a></li>
			<li><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Sản Phẩm</a></li>
			<li><a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Danh Mục</a></li>
			<li><a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="Index">Hóa Đơn</a></li>
			<li><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Thống Kê</a></li>
			<li><a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Phiếu Chi</a></li>

		</ul>

	</nav>
</header>-->
<div class="container">
	<div class="row pt-4">
		<div class="col-1">
			<h2> Danh Mục </h2>
		</div>
		<div class="col-1 bgr-a">

			<a asp-controller="Category" asp-action="Create" class="btn btn-primary">Thêm Danh Mục</a>
		</div>
	</div>

	

	@using (Html.BeginForm())

	{

		<p>

			Nhập thông tin: @Html.TextBox("SearchString") <input type="submit" value="Tìm kiếm"  />

		</p>

	}

	<table class="table_user responsive-table">
		<thead>
			<tr>
				<th> ID</th>
				<th> Tên</th>
				<th> Sửa</th>
				<th> Xóa</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>@item.CategoryID</td>
					<td>@item.CategoryName</td>
					<td>
						<div class="bgr-a">
							<a class="btn btn-primary" asp-controller="Category" asp-action="Edit" asp-route-id=@item.CategoryID>
								Sửa
							</a>
						</div>
					</td>
					<td>
						<div class="bgr-x">
							<a class="btn btn-danger" asp-controller="Category" asp-action="Delete" asp-route-id="@item.CategoryID">
								Xóa
							</a>

						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>