BNo_Face/Controllers/List_ProductController.cs
using BNo_Face.DataAccess.Data;
using BNo_Face.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BNo_Face.Controllers
{
    public class List_ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        public List_ProductController(ApplicationDbContext db)
        {
            _db = db;
        }

     
  /*      public void LoadCategory()
        {
            IEnumerable<SelectListItem> Category = _db.Categories.Select(
                u => new SelectListItem()
                {
                    Text = u.CategoryName,
                    Value = u.CategoryID.ToString()
                }).ToList();
            ViewBag.Category = Category;
        }*/
        public void LoadProduct()
        {
            IEnumerable<SelectListItem> Product = _db.Products.Select(
                u => new SelectListItem()
                {
                    Text = u.ProductName,
                    Value = u.ProductID.ToString()
                }).ToList();

            ViewBag.Product = Product;
        }

        public IActionResult Index()
        {
            LoadProduct();
            return View();
        }

        public IActionResult Create()
        {
            LoadProduct();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(List_Product list_Product)
        {
            LoadProduct();
            if (ModelState.IsValid)
            {

                _db.List_Products.Add(list_Product);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(list_Product);
        }


    }
}

BNo_Face/Views/List_Product/Create.cshtml
@model List_Product

<h1> Thanh Toán</h1>
<form method="post" asp-action="Index">
	<div class="container">
<!--	<div class="mb-3">
			<div class="test">
				<label asp-for="Product.Category.CategoryID" class="title_block"></label>
				<select asp-for="Product.Category.CategoryID" asp-items="ViewBag.Category" class="textbox">
				</select>
			</div>
			<span asp-validation-for="Product.Category.CategoryID" class="text-danger"></span>
				</div>-->
		<div class="mb-3">
			<div class="test">
				<label asp-for="Product.ProductName" class="title_block"></label>
				<select asp-for="ProductID" asp-items="ViewBag.Product" class="textbox">
				</select>
			</div>
			<span asp-validation-for="ProductID" class="text-danger"></span>
		</div>
	<!--<div class="mb-3">
			<div class="test">
			<label asp-for="Product.Price" class="title_block"></label>
			<input asp-for="Product.Price" class="textbox" /> <br />
			<input asp-for="Product.Price" type="hidden" />
			<span class="textbox BorderShow">Model.Product.Price</span>
			</div>
			<span asp-validation-for="Product.Price" class="text-danger"></span>
			</div>-->
		<div class="mb-3">
			<div class="test">
				<label asp-for="Quantity" class="title_block"></label>
				<input type="number" class="form-control textbox" />
			</div>
			<span asp-validation-for="Quantity" class="text-danger"></span>
		</div>

		<div class="bgr-bt">
			<button type="submit" class="btn btn-primary">Thêm</button>
			<button class="btn btn-primary" asp-controller="List_Product" asp-action="Index">Trở về</button>
		</div>
	</div>
</form>

BNo_Face/Views/List_Product/Index.cshtml
@model IEnumerable<List_Product>

<div class="container">
	<div class="row pt-4">
		<div class="col-1">
			<h2> Hóa Đơn</h2>
		</div>
		<div class="col-1 bgr-a">

			<a asp-controller="List_Product" asp-action="Create" class="btn btn-primary">Thêm Sản Phẩm</a>
			<br />
		</div>
		<div class="Tb-Container">
			<table class="table_user responsive-table">
				<thead>
					<tr>
						<th>Tên sản phẩm</th>
						<th>Số lượng</th>
						<th>Giá</th>
						<th>Thành tiền</th>
					</tr>
				</thead>
				<tbody>
					@if(Model != null)
					{
						@foreach (var i in Model)
						{
							var ThanhTien = i.Quantity * i.Product.Price;
							decimal total = 0;
							total += ThanhTien;
							<tr>
								<td>@i.Product.ProductName</td>
								<td>@i.Quantity</td>
								<td>@i.Product.Price</td>
								<td>@(ThanhTien.ToString("n0"))</td>
								<td>
									<div class="bgr-a">
										<a class="btn btn-primary" asp-controller="List_Product" asp-action="Edit" asp-route-id="@i.ProductID">
											Sửa
										</a>
									</div>
								</td>
								<td>
									<div class="bgr-x">
										<a class="btn btn-danger" asp-controller="List_Product" asp-action="Delete" asp-route-id="@i.ProductID">
											Xóa
										</a>

									</div>
								</td>
							</tr>
						}

					}
					else
					{
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					}

				</tbody>
			</table>
		</div>
	</div>
	<div class="bgr-bt">
        <button type="submit" class="btn btn-primary">Thanh toán</button>
	</div>

</div>